# Header
menu:
  C/C++:
     Code expt - Tcp Socket: /tcp-sock/
     Code expt - Console Interaction: /cli-int/
     Code expt - Embedded-ADT: /embed-adt/
     Code expt - cmocka explore: /cmocka-exp/
     Code rev - paho.mqtt.c: /paho-mqtt-c-notes/
     Code sum - tricks: /c-usage/
     Code sum - basics: /c-basics/
  Book notes:
     PSICC2: /psicc2-notes/
     Nand2Tetris: /nand2tetris/
     TLPI: /linux-p-int/
  Linux:
     Shell commands: /linux-cmd/
  Leetcode:
  IoT notes:
     SDK review: /sdk-review/
     Data model analysis: /data-model/

extmenu:
     github: //github.com/TonyZhaoyu/

# Content
excerpt_link: Read More

fancybox: true

# Miscellaneous
google_analytics:
google_universal_analytics:
rss:
