# Header
menu:
  C Apps:
     Expt - Tcp Socket: /tcp-sock/
     Expt - Console Interaction: /cli-int/
     Expt - Embedded-ADT: /embed-adt/
     Expt - Cmocka explore: /cmocka-exp/
     Rev - Paho.mqtt.c: /paho-mqtt-c-notes/
     C_Tricks: /c-usage/
     C_Basics: /c-basics/
  Book notes:
     PSICC2: /psicc2-notes/
     Nand2Tetris: /nand2tetris/
     TLPI: /linux-p-int/
  Linux:
     Shell commands: /linux-cmd/
     Kernel rev - typeof: /kernel-rev-typeof/
     Kernel rev - rbTree: /kernel-rev-rbtree/
  Leetcode:
  IoT notes:
     SDK review: /sdk-review/
     Data model analysis: /data-model/

extmenu:
     github: //github.com/TonyZhaoyu/

# Content
excerpt_link: Read More

fancybox: true

# Miscellaneous
google_analytics:
google_universal_analytics:
rss:
